### PR TITLE
Damage implementation

### LINKED ISSUE #16: Negative health
On the scoreboard the health meter is able to go negative. If the health meter reaches a value of -100 it crashes.

### LINKED ISSUE #57: Damage Implementation
The full calculation of damage including armor, skill modifiers, weapon (type,level) will need to be implemented for both NPC->Player and Player->NPC.

- [x] Ignore Minecraft damage
- [x] NPC -> Player attack damage
- [x] Player -> NPC attack damage
- [x] Effective damage calculation
- [x] Player health/death management

### PR DESCRIPTION
**Pull request by JeromSar**
This PR includes a reworked damage implementation. Currently, only armor reduction is missing.
However, this PR needs to be tested thoroughly in order to be merged. For the testers, please check if the following is done correctly on this branch:
* Damage calculation (especially on custom items)
* Knockback
* Health updating

Thanks!

Squash commit:
```
Added damage implementation. Closes #57 and fixes #16
Health is currently updated manually, but might need to be changed with a new GUI manager.
Adjusted mobspawn profile to improve clarity.
```

### CODE REVIEW

File: src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java [hunk 1]
```diff
@@ -86,21 +86,35 @@ protected void onStart() {
...
+            // Load metadata from this section
+            // Most importantly: name, level, (armor type), tier, and lore
+            meta.loadFrom(section);
+
+            // Validate armor type
+            if (meta.getArmorType() != null && !InventoryUtil.isArmor(type)) {
+                logger.warning("Skipping item: " + id + ". Armor type specified for non-armor!");
+                continue;
+            }
+            if (meta.getArmorType() == null && InventoryUtil.isArmor(type)) {
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java:110]: isnt this also neccesary for weapons?

**Review by cashenkes — COMMENTED** [review]
just leaving a comment for now, nearly done reviewing the whole thing.

File: src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java (hunk 1 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java:110]: @cashenkes I don't think so. Weapons don't have a heavy/light variant defined right now. This line just ensures that either the type is armor, and we have specified weather its light/heavy armor, or that the type is not armor, and there is no heavy/light defined.

File: src/main/java/net/goldiriath/plugin/game/damage/DamageManager.java [hunk 2]
```diff
@@ -0,0 +1,293 @@
...
+            return;
+        }
+
+        if (!(event.getEntity() instanceof Player)) {
+            return;
+        }
+
+        // Disable PvP for now
+        event.setCancelled(true);
+        ((Player) event.getDamager()).sendMessage(ChatColor.RED + "PvP is disabled in this area.");
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/damage/DamageManager.java]: maybe the message should be changed to PvP is not enabled in alpha, since this sentence could imply a PvP area existing, but we do not have one (minor thing)

File: src/main/java/net/goldiriath/plugin/game/damage/DeathManager.java [hunk 3]
```diff
@@ -52,6 +53,8 @@ public void onPlayerDeath(PlayerDeathEvent event) {
             if (money < deathCost) {
                 player.sendMessage(ChatColor.RED + "You lost your items because you didn't have enough money.");
                 event.setKeepInventory(false);
+                // TODO: Drop items, but remove skills
+                event.getDrops().clear();
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/damage/DeathManager.java]: cant this todo already be fixed?

File: src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java [hunk 4]
```diff
@@ -112,13 +126,7 @@ protected void onStart() {
...
             }
             bMeta.setDisplayName(sb.toString());
-
-            // Data value
-            stack.getData().setData(data);
-
-            // Enchantments
-            stack.addEnchantments(enchantments);
-
+             */
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java]: should this commented code be removed? (line 115 to line 129)

File: src/main/java/net/goldiriath/plugin/game/loot/LootManager.java [hunk 5]
```diff
@@ -109,38 +108,27 @@ protected void onStop() {
...
         if (loot == null) {
-            logger.warning(player.getName() + " killed NPC that does not have a loot profile!");
             return;
         }
 
-        List<ItemStack> drops = loot.drop(profile.getTier());
-        player.getInventory().addItem(drops.toArray(new ItemStack[]{}));
+        Player lastAttacker = plugin.getServer().getPlayer(trait.getLastAttacker());
+        List<ItemStack> drops = loot.drop(profile.getLootTier());
+        lastAttacker.getInventory().addItem(drops.toArray(new ItemStack[]{}));
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/loot/LootManager.java]: Seemingly only the player that did the last hit gets loot form the mob, this might not be something we want.

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java [hunk 6]
```diff
@@ -37,20 +38,23 @@
...
+    private int health;
     @Getter
-    private ItemStack item;
-    private long spawnThreshold;
+    private MobTier lootTier;
     @Getter
-    private ItemStack carryItem;
+    private LootProfile lootProfile;
+    @Getter
+    private ItemStack hand;
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:57]: Here you het getters for the items that a mob hes, is it possible to give mobs shields? and if yes do we want that, since that seems impossible with this implementation.

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java [hunk 7]
```diff
@@ -150,30 +148,81 @@ public NPC spawn(Location location) {
...
+
+        // Stats
+        level = config.getInt("stats.level", -1);
+        if (level == -1) {
+            logger.warning("Could not load mobspawn profile '" + id + "'. Level field not present.");
+        }
+        damage = config.getInt("stats.damage", -1);
+        health = config.getInt("stats.health", -1);
+        if (health == -1) {
+            logger.warning("Could not load mobspawn profile '" + id + "'. Health field not present.");
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:181]: should the mob still be spawned if the health value is not loaded correctly? since it now seems to continue. (same question for type and level)

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java [hunk 8]
```diff
@@ -150,30 +148,81 @@ public NPC spawn(Location location) {
...
+            hand = Util.parseItem(config.getString("items.hand", null));
+            helmet = Util.parseItem(config.getString("items.helmet", null));
+            chestplate = Util.parseItem(config.getString("items.chestplate", null));
+            leggings = Util.parseItem(config.getString("items.leggings", null));
+            boots = Util.parseItem(config.getString("items.boots", null));
+        }
+
+        if (damage == -1 && hand == null) {
+            logger.warning("Could not load mobspawn profile '" + id + "'. Damage field not present and item not present. Must specify either to calculate attack damage.");
+        }
```
Comment (cashenkes) [inline src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:221]: here again, there is a warning given, but the method still continues, is that alright?

**Review by cashenkes — COMMENTED** [review]
I left some questions, please look at those.

File: src/main/java/net/goldiriath/plugin/game/damage/DamageManager.java (hunk 2 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/damage/DamageManager.java]: I agree.

File: src/main/java/net/goldiriath/plugin/game/damage/DeathManager.java (hunk 3 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/damage/DeathManager.java]: Yes, will do so.

File: src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java (hunk 4 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/item/CustomItemManager.java]: Yes, will do.

File: src/main/java/net/goldiriath/plugin/game/loot/LootManager.java (hunk 5 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/loot/LootManager.java]: @cashenkes What do you think is appropriate here? Divide the drops randomly among all players whom have attacked the mob? What about parties? What if aiding players did not do direct damage, but did help (e.g. healers)?

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java (hunk 6 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:57]: @cashenkes Currently this is not supported. Do we need this functionality for Alpha?

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java (hunk 7 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:181]: @cashenkes The mob is not spawned. The `loadFrom` method always succeeds. However, this does not mean that the mobspawn profile is valid. There is an `isValid` method which is called before the mobspawn is added. See https://github.com/Goldiriath/Goldiriath/pull/68/files/611d9d1e81454a082c34a9f3ac9a4cd5a6038676#diff-21574682e7b72292cb3ce93e74dc21aaR360 If the health value is not set properly, the `isValid` method returns false and the mobspawn profile is not added to the list of currently loaded profiles.

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java (hunk 8 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:221]: Same here, as above.

**Comment by JeromSar** [comment]
@cashenkes I will perform the fixes you indicated asap.

File: src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java (hunk 6 above)
Comment (cashenkes) [reply src/main/java/net/goldiriath/plugin/game/mobspawn/MobSpawnProfile.java:57]: Not neccesary for alpha, but I think it would be nice to have it at some point.

File: src/main/java/net/goldiriath/plugin/game/loot/LootManager.java (hunk 5 above)
Comment (JeromSar) [reply src/main/java/net/goldiriath/plugin/game/loot/LootManager.java]: Associated issue: https://github.com/Goldiriath/Goldiriath/issues/71

**Comment by JeromSar** [comment]
@cashenkes Requested changes have been made. Ready for your review and individual testing.
@KoenduBuf Would like to see your review here too.
